# Use Ubuntu 24.04 as base image
FROM ubuntu:jammy

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get clean && apt-get update && apt-get install -y \
    git \
    build-essential \
    cmake \
    python3-dev \
    python3-venv \
    python3-pip \
    # python3.8-dev \
    # libpython3.8-dev \
    # python3-opencv \
    libudev-dev \
    ffmpeg \
    udev \
    usbutils \
    libxcb-xinerama0 \
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    libportaudio2 \
    alsa-base \
    alsa-utils \
    python3-tk \
    && rm -rf /var/lib/apt/lists/*

#######################################
## Python dependencies and SDK setup ##
#######################################

# 1. Create the venv
RUN python3 -m venv --system-site-packages /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# 2. Install dependencies (minus the Orbbec source build for a moment)
RUN pip install --upgrade pip && \
    pip install paho-mqtt ollama sounddevice scipy pillow matplotlib typing pybind11 pyorbbecsdk2 opencv-python-headless faster-whisper

WORKDIR /app
CMD ["python3", "inference_ollama.py"]