version: "3"

services:
  mqtt:
    image: eclipse-mosquitto:2.0.18
    ports:
      - 1883:1883
      - 9001:9001
      - 8080:8080
    volumes:
      - ./mqtt/mosquitto-config:/mosquitto/config/
      - ./mqtt/auth:/auth 

# By using --device-cgroup-rule flag we grant the docker continer permissions -
# to the camera and usb endpoints of the machine.
# It also mounts the /dev directory of the host platform on the container 
  vision-orbbec:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - .:/ultralytics/pyorbbecsdk/app
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix # needed to show results on screen
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    environment:
      - DISPLAY=$DISPLAY  # needed to show results on screen
      - XAUTHORITY=$XAUTHORITY  # needed to show results on screen

    restart: unless-stopped